---
title: "Publications"
format: html
---
[Google Scholar](https://scholar.google.com/citations?user=hvNlugEAAAAJ&hl=en)

## Preprints:

-   [Gaidatzis D^1,2^, Graf-Landua M^1^, Methot SP^1^, Woelk M, Brancati G, Hauser YP, Meeuse M,  Nahar S, Braun K, van der Does M, Aluri S, Kohler H, Smallwood S, Grosshans H^2^. A scheduler for rhythmic gene expression. bioRxiv. September, 2025. ^1^equal contribution ^2^co-corresponding](https://doi.org/10.1101/2025.09.04.674194)

-   [Olver J, Shtumpf M, Hussain K, Methot SP, Sarkies P, Ferreira HC. ATRX safeguards cellular identity during C. elegans development. bioRxiv. March, 2025.](https://doi.org/10.1101/2025.03.11.641662)

## Postdoc:

-	[Delaney CE, Methot SP, Kalck V, Seebacher J, Hess D, Gasser SM, Padeken J. SETDB1-like MET-2 promotes transcriptional silencing and development independently of its H3K9me-associated catalytic activity. Nature Structure & Molecular Biology. February, 2022. 29(2): 85-96.](https://doi.org/10.1038/s41594-021-00712-4)

-	[Methot SP^1^, Padeken J^1^, Brancati G, Zeller P, Delaney CE, Gaidatzis D, Kohler H, van Oudenaarden A, Grosshans H, Gasser SM. H3K9me selectively blocks transcription factor activity and ensures tissue integrity. Nature Cell Biology. November, 2021. 23(11): 1163-1175. ^1^equal contribution.](https://doi.org/10.1038/s41556-021-00776-w)

-	[Padeken J, Methot SP, Zeller P, Delaney CE, Kalck V, and Gasser SM. Argonaute NRDE-3 and MBT domain protein LIN-61 redundantly recruit an H3K9me3 HMT to prevent embryonic lethality and transposon expression. Genes and Development. January, 2021. 35: 82-101.](https://doi.org/10.1101/gad.344234.120)

-	[Delaney CE^1^, Methot SP^1^, Guidi M^1^, Katic I, Gasser SM, Padeken J. Heterochromatic foci and transcriptional repression by an unstructured MET-2/SETDB1 co-factor LIN-65. Journal of Cell Biology. March, 2019. 218(3): 820-838. ^1^equal contribution.](https://doi.org/10.1083/jcb.201811038)

-	[Padeken J^1^, Zeller P^1^, Towbin B, Katic I, Kalck V, Methot SP and Gasser SM. Synergistic lethality between BRCA1 and H3K9me2 loss reflects satellite derepression. Genes and Development. April, 2019. 33: 436-451. ^1^equal contribution.](https://doi.org/10.1101/gad.322495.118) 

## PhD and prior:

-	[Litlzer LC^1^, Zahn A^1^, Dionne KL, Sprumont A, Ferreira SR, Slattery MRF, Methot SP, Patenaude AM, Hebert S, Kabir N, Subramani PG, Jung S, Richard S, Kleinman CL, Di Noia JM. Protein arginine methyltransferase 1 regulates B cell fate after positive selection in the germinal center in mice. Journal of Experimental Medicine. April, 2023. 220(9): e20220381. ^1^equal contribution.](https://doi.org/10.1084/jem.20220381)

-	[Morande PB, Yan XJ, SepulvedaJ, Seija N, Marquez ME, Sotelo N, Abreu C, Crispo M, Fernández-Graña G, Rego N, Bois T, Methot SP, Palacios F, Remedi V, Rai KR, Buschiazzo A, Di Noia JM, Navarrete MA, Chiorazzi N, Oppezzo P. AID overexpression leads to aggressive murine CLL and non-Ig mutations that mirror human neoplasms. Blood. March 4, 2021.](https://doi.org/10.1182/blood.2020008654)

- [Litlzer LC, Zahn A, Meli AP, Hebert S, Patenaude AM, Methot SP, Sprumont A, Bois T, Kitamura D, Constantino S, King IL, Kleinman CL, Richard S, Di Noia JM. PRMT5 is essential for B cell development and germinal center dynamics. Nature Communications. January 3, 2019. 10: Article 22.](https://doi.org/10.1038/s41467-018-07884-6)

-	[Methot SP^1^, Litzler LC^1^, Subramani PG, Eranki AK, Fifield H, Patenaude A-M, Gilmore JC, Bagci H, Santiago GE, Côté JF, Larijani M, Verdun RE, Di Noia JM. A licensing step links AID to transcription elongation for B cell mutagenesis. Nature Communications. March, 2018. 9: Article 1248. ^1^equal contribution.](https://doi.org/10.1038/s41467-018-03387-6)

-	[Methot SP, Litzler LC, Trajtenberg F, Zahn A, Robert F, Pelletier J, Buschiazzo A, Magor BG, Di Noia JM. Consecutive Interactions with HSP90 and eEF1A1 Underlie a Functional Maturation and Storage Pathway of AID in the Cytoplasm. Journal of Experimental Medicine. April, 2015. 212(4): 581-596.](https://doi.org/10.1084/jem.20141157)

-	[Zahn A^1^, Eranki AK^1^, Patenaude AM, Methot SP, Fifield H, Cortizas EC, Foster P, Imai K, Durandy A, Larijani M, Verdun RE, Di Noia JM. Activation Induced Deaminase Prevents End Resection and Promotes End Joining During Class Switch Recombination. PNAS. March, 2014. 111(11): E988-E997. ^1^equal contribution.](https://doi.org/10.1073/pnas.1320486111)

-	[Baker JHE, Kyle AH, Bartels KL, Methot SP, Flanagan EJ, Babirnie A, Cran JD and Minchinton AI. Targeting the Tumour Vasculature: Exploitation of Low Oxygenation and Sensitivity to NOS Inhibition by Treatment with a Hypoxic Cytotoxin. PLoS One. October, 2013. 8(10): e76832.](https://doi.org/10.1371/journal.pone.0076832)

-	[Hu Y, Ericsson I, Torseth K, Methot SP, Sundheim O, Liabakk NB, Slupphaug G, Di Noia JM, Krokan HE and Kavli B. A Combined Nuclear and Nucleolar Localization Motif in Activation-Induced Cytidine Deaminase (AID) Controls Immunoglobulin Class Switching. Journal of Molecular Biology. January, 2013. 425(2): 424-443.](https://doi.org/10.1016/j.jmb.2012.11.026)

-	[Orthwein A, Zahn A, Methot SP, Godin D, Conticello SG, Terada K, Di Noia JM. Optimal functional levels of activation-induced deaminase specifically require the Hsp40 DnaJa1. EMBO J. February, 2011. 31(3): 679-691.](https://doi.org/10.1038/emboj.2011.417)

-	[Poon L, Methot SP, Morabi-Pazooki W, Pio F, Bennet A, Sen D. Guanine-rich RNAs and DNAs that bind heme robustly catalyze oxygen transfer reactions. Journal of the American Chemical Society. February, 2011. 133(6): 1877-1884.](https://doi.org/10.1021/ja108571a)

## Review Articles and book chapters:

-	[Padeken J, Methot SP and Gasser SM. Establishment of H3K9-methylated heterochromatin and its functions in tissue differentiation and maintenance. Nature Reviews Molecular Cell Biology. September, 2022. 23(9): 623-640.](https://doi.org/10.1038/s41580-022-00483-w)

-	[Methot SP^1^ and Di Noia JM^1^. Molecular Mechanisms of Somatic Hypermutation and Class Switch Recombination. Advances in Immunology. January, 2017. 133: 37-87. ^1^co-corresponding.](https://doi.org/10.1016/bs.ai.2016.11.002)

-	[Methot SP and Di Noia JM. Pharmacological manipulation of AID. Oncotarget. September, 2015. 6(29): 26550.](https://doi.org/10.18632/oncotarget.5269)

## Patents:

-	[Di Noia JM, Verdun RE, Methot SP. Modulating uracil-dna glycosylase and uses thereof.<br> Patent # US20180221438A1.](https://patents.google.com/patent/US20180221438A1/en)

